# Build-CapStone-May2023-DataPirates

trigger:
- DataPirates

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  buildSolution: 'BackEnd/CapstoneProject.sln'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build CapStone-May2023-DataPirates'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish CapStone-May2023-DataPirates'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'CapStone-May2023-DataPirates'
    publishLocation: 'Container'
