trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      cd '$(System.DefaultWorkingDirectory)/FrontEnd'
      npm install -g @angular/cli
      npm install
      ng build --prod
    displayName: 'npm install and build'


- task: Npm@1  
  displayName: 'Angular CLI 13.2.5'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install -g @angular/cli@13.2.5'
 
- task: Npm@1  
  displayName: 'npm install'  
  inputs:
    command: custom  
    customCommand: 'install file:custom-angular-lib.tgz --legacy-peer-deps'  
   
- task: Npm@1  
  displayName: Build  
  inputs: 
    command: custom  
    verbose: false  
    customCommand: 'run build'  
  

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/FrontEnd/dist/FrontEnd/'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true
    displayName: 'Archive files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'



  - task: Npm@1  
        displayName: Build  
        inputs:
          command: custom  
          customCommand: 'run build'  
        
      - task: CopyPublishBuildArtifacts@1  
        displayName: 'Copy Publish Artifact: angular-web-app'  
        inputs:  
          CopyRoot: /dist  
          Contents: '**'  
          ArtifactName: angular-web-app 
          ArtifactType: Container
