/**
 * Capstone Project
 * Capstone Project - ToDos List
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class User { 
    id?: string | null = "";
    UserviewId?: string | null = "";
    firstName?: string = "";
    lastName?: string = "";
    email?: string = "";
    phoneNumber?: string = "";
    password?: string = "";
    confirmPassword?: string = "";
    accessToken?: string = "";
}